# Run unittests

name: test

# Allow to trigger the workflow manually (e.g. when pushing changes to `etils`)
on: [push, workflow_dispatch]

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    # Install deps
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: pip install -e .
    - run: pip install -e .[dev]  # Install dev requirements

    - name: Run core tests
      run: |
        pytest -vv -n auto \
          --ignore="jax3d/visu3d" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-True-True-pytree]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-True-True-array]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-True-True-empty]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-True-False-pytree]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-True-False-array]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-True-False-empty]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-False-True-pytree]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-False-True-array]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-False-True-empty]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-False-False-pytree]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-False-False-array]" \
          --deselect="jax3d/math/volume_rendering_test.py::test_volume_rendering[float64-False-False-empty]"
